use_frameworks!

platform :ios, '13.0'

target 'IssmContactlessBiometric_Example' do
  pod 'IssmContactlessBiometric', :path => '../'

  target 'IssmContactlessBiometric_Tests' do
    inherit! :search_paths

    
  end
end
